In [1]:
# SORU 1.1
notlar = [85, 92, 76, 92, 100, 76, 85, 92]

benzersiz = list(set(notlar))
print("Benzersiz:", benzersiz)

Benzersiz: [100, 92, 85, 76]


In [3]:
# SORU 1.2
# En yüksek ve en düşük
print("En yüksek:", max(notlar))
print("En düşük:", min(notlar))

En yüksek: 100
En düşük: 76


In [5]:
# SORU 1.3
# Küçükten büyüğe sıralama
sirali = sorted(notlar)
print("Sıralı:", sirali)

Sıralı: [76, 76, 85, 85, 92, 92, 92, 100]


In [7]:
def armstrong_mu(sayi):
    basamaklar = [int(d) for d in str(sayi)]
    toplam = sum([b**3 for b in basamaklar])
    return toplam == sayi

print(153, armstrong_mu(153))
print(123, armstrong_mu(123))

153 True
123 False


In [9]:
# SORU 3
A = {"Python", "R", "SQL", "Java"}
B = {"C++", "Python", "JavaScript", "SQL"}

print("Ortak:", A & B)
print("Sadece A’da:", A - B)
print("Birleşim (alfabetik):", sorted(A | B))

Ortak: {'Python', 'SQL'}
Sadece A’da: {'Java', 'R'}
Birleşim (alfabetik): ['C++', 'Java', 'JavaScript', 'Python', 'R', 'SQL']


In [11]:
# SORU 4
import random, statistics

sayilar = [random.randint(1,100) for _ in range(10)]
print("Sayılar:", sayilar)
print("Ortalama:", statistics.mean(sayilar))
print("Standart Sapma:", statistics.stdev(sayilar))

Sayılar: [19, 8, 53, 58, 25, 45, 26, 55, 52, 82]
Ortalama: 42.3
Standart Sapma: 22.321140950527894


In [13]:
# SORU 5
def kelime_sayaci(metin):
    kelimeler = metin.split()
    en_uzun = max(kelimeler, key=len)
    en_sik = max(set(kelimeler), key=kelimeler.count)
    return len(kelimeler), en_uzun, en_sik

print(kelime_sayaci("veri bilim veri python analiz veri"))

(6, 'python', 'veri')


In [15]:
# SORU 6
sayilar = [5, 12, 7, 18, 24, 3, 16]

ciftler = list(filter(lambda x: x%2==0, sayilar))
kareler = list(map(lambda x: x**2, ciftler))
sirali = sorted(kareler, reverse=True)

print("Çiftler:", ciftler)
print("Kareler:", kareler)
print("Azalan kareler:", sirali)

Çiftler: [12, 18, 24, 16]
Kareler: [144, 324, 576, 256]
Azalan kareler: [576, 324, 256, 144]


In [17]:
# SORU 7
kelimeler = ["veri", "bilim", "analiz", "yapayzeka", "jupyter"]
sirali = sorted(kelimeler, key=lambda x: len(x))
print(sirali)

['veri', 'bilim', 'analiz', 'jupyter', 'yapayzeka']


In [19]:
# SORU 8
def rakam_toplami(s):
    rakamlar = [int(ch) for ch in s if ch.isdigit()]
    return sum(rakamlar)

print(rakam_toplami("abc12def3"))

6


In [21]:
# SORU 9 
import numpy as np

dizi = np.random.randint(0,51,10)
print("Dizi:", dizi)
print("Ortalama:", dizi.mean())
print("Std Sapma:", dizi.std())
print("En büyük:", dizi.max())

Dizi: [11  4 23 40 24 48  4 23 34 25]
Ortalama: 23.6
Std Sapma: 13.792751719653335
En büyük: 48


In [23]:
# SORU 10  
matris = np.random.rand(5,5)
print("Matris:\n", matris)
print("Sütun ortalamaları:", matris.mean(axis=0))

binary = (matris > 0.5).astype(int)
print("Binary matris:\n", binary)

Matris:
 [[0.24065411 0.32780254 0.93365444 0.27742777 0.9558067 ]
 [0.77564842 0.14105617 0.53269341 0.79014477 0.75864057]
 [0.05158862 0.71111543 0.06974874 0.00614631 0.97826275]
 [0.68805592 0.21499717 0.61543566 0.56799195 0.05203864]
 [0.57109866 0.28516429 0.05465656 0.50857715 0.65810049]]
Sütun ortalamaları: [0.46540915 0.33602712 0.44123776 0.43005759 0.68056983]
Binary matris:
 [[0 0 1 0 1]
 [1 0 1 1 1]
 [0 1 0 0 1]
 [1 0 1 1 0]
 [1 0 0 1 1]]
